go/bubble-sort-algorithm.go
=> Bubble sort algorithm in Go

Python/bubble_sort.py
=> Add bubble sort in python

swift/bubble_sort/bubble_sort.swift
added swift directory with bubble sort algo implementation in swift
=> implements bubble sort algo in swift

algorithms/search/binary_search/ruby/binary_search.rb, algorithms/sort/bubble_sort/ruby/bubble_sort.rb, algorithms/sort/merge_sort/ruby/merge_sort.rb, algorithms/sort/quick_sort/ruby/quick_sort.rb, algorithms/sort/selection_sort/ruby/selection_sort.rb
Hi there!
This adds new Ruby algorithms:
- Binary Search
- Bubble Sort
- Merge Sort
- Quick Sort
- Selection Sort
=> Add Ruby algorithms

algorithms/sort/bubble_sort/kotlin/bubblesort.kt
Added the bubble sort algorithm in kotlin language. Please review :-)
References issue #6 
Thanks
=> Bubble Sort algorithm in kotlin added

.gitignore, algorithms/sort/bubble_sort/java/GenericBubbleSort.java
Added a generic version of bubble sort. so that bubble sort can run on all types that inherit comparable.
=> Added a generic version of bubble sort

algorithms/Dynamic/src/LongestCommonSubString.java
=> Adding dynamic programing.

algorithms/sort/selection_sort/java/SelectionSort.java
=> Selection Sort in java

data_structures/queue/queue/java/IterableQueue.java
This class implements Iterable interface. For #14
=> Added queue data structure in java

algorithms/sort/bubble_sort/README.md, algorithms/sort/bubble_sort/elixir/README.md, algorithms/sort/bubble_sort/elixir/bubblesort.ex
#6 Added an Elixir implementation of the bubble sort algorithm
=> added Elixir version of bubble sort

data_structures/queue/queue/kotlin/IterableQueue.kt
=> Added queue data structure in kotlin

algorithms/sort/bucket_sort/bucket_sort.cpp, algorithms/sort/bucket_sort/bucket_sort.java
Added bucket sort algorithm in cpp and java
=> Added bucket sort in cpp and java

data_structures/bloom_filter/bloom_filter.py
New data structure: bloom filter in python 3
=> Added bloom filter in Python 3

data_structures/binary_tree/bfs in binary tree
Breadth first search to search the element in a tree and print the path.
=> bfs to search element in a tree

data_structures/graphs/graph.py
=> graph_implemented

data_structures/hash_table/java/Hash_table.java
Implementation of Hash Table in Java using an array of linked list. Contains functions like get, put, display, remove etc.
=> Hash Table in Java

data_structures/heap/java/Heap.java
Contains Functions like add, remove, isLarger, Swap etc. in Java.
=> Added Heap in Java

data_structures/generic_tree/Java/gt.java, data_structures/heaps/java/heaps.java
Implementation of generic trees and heaps and their basic functions in java
=> Implementation of generic trees and heaps in java

algorithms/sort/quick_sort/cpp/quickSort.cpp
Link to IDEone: https://ideone.com/9G0hgT
=> Creating QuickSort algorithm for C++

algorithms/bogo_sort/java/BogoSort.java
Added bogo sort to algorithms list
=> Add bogo sort in Java

algorithms/quick_sort/ada/quick_sort.adb
Added Quick Sort code in Ada #59
=> algorithms/quick-sort/ada: Implement QuickSort in Ada

algorithms/sieve_of_eratosthenes/java/sieve.java
Hey @BaReinhard,
I have added the algorithm for finding primes less than or equal to a given number in java. Please review the same.
=> Algorithm for sieve of eratosthenes added

algorithms/bucket_sort/bucket_sort.py
This pull request adds python code for bucket sort.
=> Bucket sort python code

algorithms/binary_search/cpp/binary_search.cpp
Added the binary search algorithm in cpp language.
=> Added binary search in cpp

algorithms/permutations/java/Permutation.java
=> added permutations algo in java using backtracking

algorithms/heap_sort/javascript/heap_sort.js
=> Added heap sort in JavaScript

algorithms/binary_search/javascript/binary_search.js
=> Added binary search in JavaScript

algorithms/linear_search/javascript/linear_search.js
=> Added linear search in JavaScript

algorithms/matrix_chain_multiplication/python/MCM.py, algorithms/tower_of_hanoi/python/tower_of_hanoi.py
Added Matrix chain multiplication in python #59
=> Added Matrix chain multiplication in python

algorithms/selection_sort/javascript/selection_sort.js
=> Added selection sort in JavaScript

algorithms/bitwise/cpp/generating_subsets.cpp
Added algorithm to generate subsets using bit manipulation in C++
=> Generating Subsets in C++

algorithms/insertion_sort/cpp/insertion_sort.cpp
=> added insertion sort in c++

data_structures/mirror_of_a_tree.java/java/Mirror.java
#59 
Mirror of a tree in java #
=> added mirror of a tree in data structures in java

algorithms/dynamic_programming/c/0_1_knapsack_problem.c, algorithms/dynamic_programming/c/count_no_of_ways_to_reach_nth_stair.c, algorithms/dynamic_programming/c/longest_pallindrome_sequence.c
1. Count number of ways to reach nth stair
2. Longest Pallindrome Sequence
2. 0-1 Knapsack Problem
=> Added some famous Dynamic Programming Coding Solutions

algorithms/closest/java/Closest.java
This algorithm finds the closest distance between two elements in a given list.
=> Created Closest algorithm

descriptions/binary_search_tree.md, descriptions/diameter_of_a_tree.md
=> Description for bst

data_structures/dimaeter_of_a_tree/cpp/Diameter.cpp
=> Diameter of a BST in cpp

data_structures/queue/c/queue.c
Queues class using c added. please review and inform about the changes to be done (if any).
=> queues class using c added

algorithms/EuclideanAlgorithm/python/euclideanAlgorithm.py
An infamous algorithm, usually taught as an example when giving the rigorous definition for an algorithm.
=> Created euclideanAlgorithm.py

data_structures/bag/java/Bag.java
Added Bag-Datastructure in Java
=> added bag data-structure

algorithms/tower_of_hanoi/javascript/tower_of_hanoi.js
=> Added Tower of Hanoi in javascript

algorithms/longest_common_subsequence/javascript/longest_common_subsequence.js
=> Added longest common subsequence in JavaScript

algorithms/bfs/cpp/bfs.cpp, algorithms/dfs/cpp/dfs.cpp
I wrote bfs and dfs algorithms in C++
=> added bfs and dfs in cpp

algorithms/insertion_sort/ada/insertion_sort.adb
Added Insertion Sort code in Ada #59
=> algorithms/insertion-sort/ada: Implement Insertion Sort in Ada

algorithms/quick_sort/javascript/quick_sort.js
implemented quicksort in javascript
Resolves #131
=> /algorithms: adds javascript/quick_sort.js

descriptions/Trie.msd, descriptions/binary_search_tree.msd, descriptions/circular_queue.msd, descriptions/diameter_of_a_tree.msd, descriptions/simple_queue.msd
=> Description-queue,cqueue,trie,bst

data_structures/linked_list/python/linked_list.py
=> Added linked list in python

algorithms/heap_sort/python/heap_sort.py
=> Added heap sort in python

algorithms/sieve_of_eratosthenes/python/sieve.py
Algorithm to run sieve of eratosthenes and find primes up to given N
=> Add sieve of eratosthenes in Python

algorithms/dynamic_programming/c/Coin_change_DP.c
Added famous, coin change Dynamic programming problem.
=> Added DP problem

algorithms/radixsort/python/lsd_radixsort.py
Issue https://github.com/BaReinhard/Hacktoberfest-Data-Structure-and-Algorithms/issues/59
=> added lsd radixsort in python3

data_structures/heap/ruby/heap.rb, data_structures/linked_list/ruby/linked_list.rb, data_structures/queue/ruby/queue.rb, data_structures/stack/ruby/stack.rb
=> Add heap, linked_list, queue, stack in Ruby

algorithms/histogram_equalization/java/HistogramEqualization.java
This pull request resolves issue #60
=> Java 8 implementation of Histogram Equalization Algorithm

algorithms/insertion_sort/ruby/insertion_sort.rb
noticed there was no insertion sort in ruby
:v:
=> Insertion Sort in Ruby

algorithms/dynamic_programming/java/MinCostPath.java
gives the minimum cost path for the provided co-ordinates.
=> added minimum cost path problem

algorithms/bellman_ford/java/BellmanFord.java
Refactored the code to allow for an easier initialization of the graph and better information hiding. Treated the cases of invalid starting node, null graph or empty graph. Fixed the message displayed in case of graph with negative cycle.
Closes #235
=> Fix bellmanford corner cases

algorithms/binary_search/java/binarysearch.java
The example in the main function was incorrect because the array has to be sorted for binary search. Also I added the treatment of the special case in which the array is empty.
Closes: #230
=> Fix binary search

data_structures/union_find/cpp/UnionFind.cpp, descriptions/union_find.md
=> Added Union Find Data structure with description of the same for ELI5

algorithms/tower_of_hanoi/php/towers_of_hanoi.php
=> towers of hanoi in php

algorithms/longest_common_substring/java/LongestCommonSubString.java
Refactor the current interface of merge sort implementation. Create a new access point for the sort method. The new method requires only the array as parameter and hence solves the problem of invalid left and right indexes (null pointer validation is also included). The access point is made static because no class level data are required in the implementation. The method is exposed as public so that it can be used from other packages.
Closes: #252
=> Fix longest common substring

algorithms/quick_sort/csharp/quicksort.cs
i have added some comments in `quicksort.cs` located at _/algorithms/quick_sort/csharp_
=> some comments are added in quicksort.cs

algorithms/shell_sort/python/shellsort.py
=> shellsort for python

algorithms/merge_sort/java/merge_sort.java
Creates a wrapper over the sort method which solves the problem of input validation.
Sets the methods to static because no class level data is required in the algorithm.
Changes the access modifier of the methods so that the functionality can be used from classes outside the package.
Closes: #244
=> Fix small errors in merge sort java

data_structures/linked_list/c/linked_list.c
Switch case is better then if-else ladder as an if-else ladder is time-consuming whereas in switch case it will skip the steps which are not required to be executed.
=> Use Switch case instead of if else ladder

data_structures/stack/go/stack.go
Stack Implementation in Golang
=> Stack implementation in Golang

data_structures/binary_search_tree/c/BSTtraversal.c, data_structures/binary_tree/c/diameterBT.c, data_structures/binary_tree/cpp/boundaryTraversal.cpp
=> added diameter of Binary tree

data_structures/hashset/java/hashset.java, data_structures/treeset/java/treeset.java
created treeset datastructure in java
=> created treeset datastructure in java

data_structures/hashset/java/hashset.java, data_structures/treemap/java/treemap.java, data_structures/treeset/java/treeset.java
=> Treemap DS in java

data_structures/hashmap/java/hashmap.java, data_structures/hashset/java/hashset.java, data_structures/treeset/java/treeset.java
=> Created Hashmap ds in java

data_structures/arraylist/java/arraylist.java, data_structures/hashset/java/hashset.java, data_structures/treeset/java/treeset.java
=> Created Arraylist ds in java

algorithms/doomsday/javascript/doomsday.js
Add Doomsday Algorithm in Javascript to [compute the day of the week](https://en.wikipedia.org/wiki/Doomsday_rule).
=> Add Doomsday Algorithm in Javascript

algorithms/dynamic_programming/c/coinChange.c, algorithms/dynamic_programming/c/longestIncreasingSubsequence.c, algorithms/dynamic_programming/c/longestRepeatedSequence.c, algorithms/dynamic_programming/c/maxSumIncSequence.c, algorithms/dynamic_programming/c/subsetSum.c, algorithms/dynamic_programming/cpp/kadens.cpp, algorithms/dynamic_programming/cpp/nCr.cpp
Added few solutions of dynamic programming problems
=> Dynamic programming

algorithms/bucket_sort/bucket_sort.c, algorithms/dynamic_programming/c/coinChange.c, algorithms/dynamic_programming/c/longestIncreasingSubsequence.c, algorithms/dynamic_programming/c/longestRepeatedSequence.c, algorithms/dynamic_programming/c/maxSumIncSequence.c, algorithms/dynamic_programming/c/subsetSum.c, algorithms/dynamic_programming/cpp/kadens.cpp, algorithms/dynamic_programming/cpp/nCr.cpp
=> Bucket sort

algorithms/kmp_search/python/KMPSearch.py
=> Add KMP search algorithm in python.

data_structures/stack/lisp/Stack.bak, data_structures/stack/lisp/Stack.rkt
Added a stack implementation in Lisp: R5RS using Dr. Racket.
=> stack: added lisp implementation

algorithms/radixsort/c++/radixsort.cpp, algorithms/shell_sort/C/ShellSort.c
I wrote the program for Shell Sort in C and for Radix Sort in C++ in different folders.
=> Added C++ file for Radix Sort and C file for Shell Sort

algorithms/strings/cpp/anagrams.cpp
I have created anagrams.cpp file in algorithms/strings/cpp
=> Add Anagrams finding algorithm in C++

algorithms/Graph/connected_components_in_undirected_graph/python/ConnectedComponents.py, data_structures/union_find/python/UnionFind.py
1. Union find DS in python 
2. An example graph algorithm in python(Finding the number of connected components in an undirected graph) 
-- Tested with cases. Good to merge.
=>  Union find DS in python and an example graph algorithm in python

.vscode/settings.json, data_structures/heap/cpp/MinHeap.h
=> Implemented MinHeap in C++
